/* Test fixtures — used ONLY in tests, never shipped as live data. */
import type {
  Agent,
  Backend,
  CapacitySnapshot,
  ProjectSnapshot,
  Settings,
  VerificationSnapshot,
} from "../lib/types";

export const projectNone: ProjectSnapshot = {
  exists: false,
  name: null,
  scheduler: {
    state: "idle",
    current_cycle: null,
    next_run_at: null,
    cooling_reason: null,
    selected_backend: null,
    project_status: "none",
    last_heartbeat: null,
  },
  eligible: true,
  eligible_reason: "eligible",
  progress: {},
  blockers: [],
  human_blockers: [],
  milestones: [],
  backlog_summary: {},
  next_task: null,
  branch: "agentic/project",
  worktree: "C:\\repo\\.agentic\\worktrees\\project",
  worktree_exists: false,
  repository_root: "C:\\repo",
  final_audit: null,
  human_decisions: [],
};

export const projectCooling: ProjectSnapshot = {
  ...projectNone,
  exists: true,
  name: "demo-app",
  scheduler: {
    ...projectNone.scheduler,
    state: "cooling",
    cooling_reason: "success",
    next_run_at: new Date(Date.now() + 10 * 60_000).toISOString(),
    selected_backend: "claude",
    project_status: "in_progress",
  },
  eligible: false,
  eligible_reason: "cooling until later (success)",
  progress: {
    tasks_total: 8,
    tasks_by_status: { done: 3, pending: 4, blocked: 1 },
    milestones: { M1: "done", M2: "in_progress" },
    backlog_complete: false,
  },
  blockers: [
    {
      task: "T-7",
      reason: "needs an API key decision",
      human_only: true,
      created_at: "2026-07-15T10:00:00",
      resolved: false,
    },
  ],
  human_blockers: [
    {
      task: "T-7",
      reason: "needs an API key decision",
      human_only: true,
      created_at: "2026-07-15T10:00:00",
      resolved: false,
    },
  ],
  milestones: [
    { id: "M1", title: "Skeleton" },
    { id: "M2", title: "Features" },
  ],
  backlog_summary: { done: 3, pending: 4, blocked: 1 },
  next_task: {
    id: "T-4",
    milestone: "M2",
    description: "implement the settings page",
    dependencies: [],
    risk: "medium",
    security_relevant: false,
    expected_size: "medium",
    status: "pending",
    attempts: 0,
    last_result: null,
    blocking_reason: null,
    acceptance_criteria: ["settings persist"],
  },
};

export const paused: ProjectSnapshot = {
  ...projectCooling,
  scheduler: {
    ...projectCooling.scheduler,
    state: "paused",
    next_run_at: null,
  },
  eligible: false,
  eligible_reason: "paused by user",
};

export const backends: Backend[] = [
  {
    name: "claude",
    type: "cli",
    classification: "cli",
    detected: true,
    version: "2.1.0",
    auth: "ok",
    models: [],
    model: null,
    smoke_test_passed: true,
    breaker_state: "available",
    unavailable_until: null,
    last_ok: "2026-07-15T09:00:00",
    last_failure_kind: null,
    consecutive_failures: 0,
    roles: ["architect", "conductor", "coder", "qa", "security"],
    is_primary: true,
    in_fallbacks: false,
    usable: true,
  },
  {
    name: "codex",
    type: "cli",
    classification: "cli",
    detected: true,
    version: "0.9.0",
    auth: "unknown",
    models: [],
    model: null,
    smoke_test_passed: false,
    breaker_state: "usage_exhausted",
    unavailable_until: new Date(Date.now() + 30 * 60_000).toISOString(),
    last_ok: null,
    last_failure_kind: "usage_limit",
    consecutive_failures: 2,
    roles: [],
    is_primary: false,
    in_fallbacks: true,
    usable: false,
  },
  {
    name: "ollama",
    type: "local",
    classification: "local",
    detected: true,
    version: "0.6.0",
    auth: "not-required",
    models: ["qwen3.5:latest"],
    model: "qwen3.5:latest",
    smoke_test_passed: true,
    breaker_state: "available",
    unavailable_until: null,
    last_ok: null,
    last_failure_kind: null,
    consecutive_failures: 0,
    roles: [],
    is_primary: false,
    in_fallbacks: true,
    usable: true,
  },
];

export const agents: Agent[] = [
  {
    id: "architect",
    name: "Project Architect",
    ai: true,
    purpose: "Turns the plan into architecture and a backlog.",
    can_edit: false,
    permissions: "read-only",
    conditional: false,
    chain: ["claude", "ollama"],
    last_invocation: "2026-07-15T08:00:00",
    last_backend: "claude",
    last_ok: true,
    recent_calls: 1,
    recent_failures: 0,
    recent_avg_duration_seconds: 42,
    recent_tokens: 12000,
    tokens_estimated: true,
  },
  {
    id: "coder",
    name: "Coder",
    ai: true,
    purpose: "Implements one work order in the worktree.",
    can_edit: true,
    permissions: "workspace-write",
    conditional: false,
    chain: ["claude", "ollama"],
    last_invocation: null,
    last_backend: null,
    last_ok: null,
    recent_calls: 0,
    recent_failures: 0,
    recent_avg_duration_seconds: null,
    recent_tokens: 0,
    tokens_estimated: false,
  },
  {
    id: "gate",
    name: "Deterministic Gate",
    ai: false,
    purpose: "Runs real checks; no model can override it.",
    can_edit: false,
    permissions: "executes configured checks",
    conditional: false,
    chain: [],
    last_invocation: null,
    last_backend: null,
    last_ok: null,
    recent_calls: 0,
    recent_failures: 0,
    recent_avg_duration_seconds: null,
    recent_tokens: 0,
    tokens_estimated: false,
  },
];

export const capacity: CapacitySnapshot = {
  note: "Subscription CLI capacity is estimated from local history unless the backend reports exact usage or reset information.",
  next_task: "T-4",
  chain: ["claude", "ollama"],
  estimate: {
    estimated_cycle_tokens: 48600,
    highest_recent_cycle_tokens: 52000,
    required_capacity_tokens: 70200,
    safety_multiplier: 1.35,
    history_samples: 3,
  },
  decision: {
    decision: "start",
    confidence: "unknown",
    selected_backend: "claude",
    required_estimated_tokens: 70200,
    available_estimated_tokens: null,
    safety_reserve_tokens: 21600,
    fallback_candidates: ["ollama"],
    wait_until: null,
    reason: "capacity unknown; proceeding conservatively",
  },
  safety_multiplier: 1.35,
  per_backend: [
    {
      name: "claude",
      calls_last_hour: 4,
      calls_last_day: 12,
      tokens_last_day: { input: 90000, cached: 20000, output: 14000, reasoning: 0 },
      tokens_estimated: true,
      limit_reasons: [],
      remaining_under_limits: null,
      limits: {},
      breaker_state: "available",
      unavailable_until: null,
    },
  ],
  recent_cycles: [
    {
      timestamp: "2026-07-15T08:30:00",
      run_id: "20260715-083000",
      backend: "claude",
      skill: "T-3",
      task_size: "medium",
      total_tokens: "52000",
      duration_seconds: "540",
      result: "success",
    },
    {
      timestamp: "2026-07-15T07:00:00",
      run_id: "20260715-070000",
      backend: "claude",
      skill: "T-2",
      task_size: "small",
      total_tokens: "31000",
      duration_seconds: "410",
      result: "failure",
    },
  ],
  moving_average_cycle_tokens: 41500,
  limit_events: [],
};

export const verification: VerificationSnapshot = {
  configured: true,
  auto_detected: true,
  commands: [
    { name: "pytest", command: "python -m pytest -q", mandatory: true },
  ],
  no_checks_is_blocking: true,
  baseline: { recorded_at: "2026-07-14T12:00:00", checks: { pytest: true } },
  latest: {
    run: "cycle-20260715-083000",
    attempt_dir: "checks-1",
    results: [
      {
        name: "pytest",
        run: "cycle-20260715-083000",
        exit_code: 0,
        passed: true,
        excerpt: "74 passed",
        known_baseline_failure: false,
        new_regression: false,
      },
    ],
  },
  qa: { event: "qa_review", verdict: "pass", run_id: "20260715-083000", ts: "2026-07-15T08:40:00" },
  security: null,
  final_audit: null,
};

export const settings: Settings = {
  interaction: { mode: "completion_only" },
  routing: {
    mode: "simple",
    primary: "claude",
    fallbacks: ["ollama"],
    per_agent: {},
  },
  cycle: { target_duration_minutes: 20, maximum_duration_minutes: 30 },
  cooling: {
    after_success_minutes: 30,
    after_failure_minutes: 30,
    minimum_minutes: 5,
    maximum_minutes: 360,
  },
  capacity: { safety_multiplier: 1.35 },
  limits: { claude: {}, codex: {}, ollama: {} },
  operating_window: {
    enabled: false,
    start: "07:00",
    stop: "22:00",
    timezone: "",
  },
  notifications: { desktop: true },
  ui: { port: 8765, open_browser: true, theme: "dark", reduced_motion: "system" },
  backends_configured: ["claude", "codex", "ollama"],
};
